title: Rainbow Pups of Utah - Events
email: rainbowpupsofutah@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Page for event details
baseurl: "/patience-tablet-freestyle-goal-banking" # the subpath of your site, e.g. /blog
url: "https://nate2014jatc.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed


timezone: America/Denver
encoding: utf-8
livereload: true
livereload_min_delay: 60
livereload_max_delay: 600
author: RaxVentus
future: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
